package com.fusionmind.ai

import android.Manifest
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.*
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.core.content.ContextCompat
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);val store=ModelStore(this);val ai=AiOrchestrator(store);val rec=WavRecorder(this);setContent{FusionMindApp(store,ai,rec)}}}
data class ChatLine(val role:String,val text:String)
enum class Tab{CHAT,CREATE,MODELS}

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun FusionMindApp(store:ModelStore,ai:AiOrchestrator,rec:WavRecorder){var tab by remember{mutableStateOf(Tab.CHAT)};var dark by remember{mutableStateOf(true)};MaterialTheme(colorScheme=if(dark)darkColorScheme()else lightColorScheme()){Scaffold(topBar={TopAppBar(title={Column{Text("FusionMind AI",fontWeight=FontWeight.Bold);Text("4 IAs locais • modo automático",style=MaterialTheme.typography.labelSmall)}},actions={TextButton(onClick={dark=!dark}){Text(if(dark)"☀" else "☾")}})},bottomBar={NavigationBar{NavigationBarItem(selected=tab==Tab.CHAT,onClick={tab=Tab.CHAT},icon={Text("✦")},label={Text("Chat")});NavigationBarItem(selected=tab==Tab.CREATE,onClick={tab=Tab.CREATE},icon={Text("▣")},label={Text("Criar")});NavigationBarItem(selected=tab==Tab.MODELS,onClick={tab=Tab.MODELS},icon={Text("⬇")},label={Text("Modelos")})}}){p->Box(Modifier.padding(p).fillMaxSize()){when(tab){Tab.CHAT->ChatScreen(ai,rec);Tab.CREATE->CreateScreen(store,ai);Tab.MODELS->ModelsScreen(store)}}}}}

@Composable private fun ChatScreen(ai:AiOrchestrator,rec:WavRecorder){val context=androidx.compose.ui.platform.LocalContext.current;val scope=rememberCoroutineScope();var input by remember{mutableStateOf("")};var busy by remember{mutableStateOf(false)};var recording by remember{mutableStateOf(false)};var img by remember{mutableStateOf<Uri?>(null)};var messages by remember{mutableStateOf(listOf(ChatLine("assistant","Olá! Eu sou o FusionMind AI. Posso conversar, analisar imagens, ouvir sua voz e gerar imagens localmente.")))};val picker=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){img=it};val mic=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){if(it){rec.start(scope);recording=true}};fun add(r:String,t:String){messages=messages+ChatLine(r,t)}
Column(Modifier.fillMaxSize()){LazyColumn(Modifier.weight(1f).fillMaxWidth().padding(horizontal=12.dp),verticalArrangement=Arrangement.spacedBy(8.dp),contentPadding=PaddingValues(vertical=12.dp)){items(messages){MessageBubble(it)};if(busy)item{LinearProgressIndicator(Modifier.fillMaxWidth())}};if(img!=null)Surface(tonalElevation=2.dp){Row(Modifier.fillMaxWidth().padding(10.dp),verticalAlignment=Alignment.CenterVertically){Text("📷 Imagem anexada",Modifier.weight(1f));TextButton(onClick={img=null}){Text("Remover")}}};Row(Modifier.fillMaxWidth().padding(10.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(6.dp)){IconButton(onClick={picker.launch("image/*")},enabled=!busy){Text("📎")};IconButton(onClick={if(!recording){if(ContextCompat.checkSelfPermission(context,Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED){rec.start(scope);recording=true}else mic.launch(Manifest.permission.RECORD_AUDIO)}else{busy=true;scope.launch{try{val f=rec.stop();recording=false;if(f!=null)input=ai.transcribe(f)}catch(t:Throwable){add("assistant","Erro de voz: ${t.message}")};busy=false}}},enabled=!busy){Text(if(recording)"■" else "🎤")};OutlinedTextField(input,{input=it},Modifier.weight(1f),placeholder={Text("Pergunte qualquer coisa…")},maxLines=5);FilledIconButton(onClick={val prompt=input.trim();if(prompt.isBlank()||busy)return@FilledIconButton;add("user",prompt);input="";busy=true;val u=img;img=null;scope.launch{try{var live="";add("assistant","");fun push(t:String){live+=t;messages=messages.dropLast(1)+ChatLine("assistant",live)};if(u!=null){val bytes=withContext(Dispatchers.IO){context.contentResolver.openInputStream(u)?.use{it.readBytes()}?:error("Imagem inválida")};ai.analyzeImage(bytes,prompt,::push)}else if(listOf("gere uma imagem","crie uma imagem","desenhe").any{it in prompt.lowercase()})messages=messages.dropLast(1)+ChatLine("assistant","Abra a aba Criar para usar o Stable Diffusion.") else ai.chat(prompt,::push)}catch(t:Throwable){messages=messages.dropLast(1)+ChatLine("assistant","Erro: ${t.message}")}finally{busy=false}}},enabled=!busy){Text("➤")}}}}
@Composable private fun MessageBubble(m:ChatLine){Row(Modifier.fillMaxWidth(),horizontalArrangement=if(m.role=="user")Arrangement.End else Arrangement.Start){Surface(shape=RoundedCornerShape(18.dp),color=if(m.role=="user")MaterialTheme.colorScheme.primaryContainer else MaterialTheme.colorScheme.surfaceVariant,modifier=Modifier.widthIn(max=560.dp)){Text(if(m.text.isBlank())"…" else m.text,Modifier.padding(12.dp))}}}
@Composable private fun CreateScreen(store:ModelStore,ai:AiOrchestrator){val context=androidx.compose.ui.platform.LocalContext.current;val scope=rememberCoroutineScope();var prompt by remember{mutableStateOf("")};var busy by remember{mutableStateOf(false)};var result by remember{mutableStateOf<android.graphics.Bitmap?>(null)};var status by remember{mutableStateOf("Stable Diffusion local • 512×512")};Column(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("Criar imagem",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text(status);OutlinedTextField(prompt,{prompt=it},Modifier.fillMaxWidth(),minLines=3,label={Text("Descreva a imagem")});Button(onClick={busy=true;scope.launch{try{val b=ai.generateImage(prompt);result=b;status="Pronto • ${saveGeneratedImage(context,b)}"}catch(t:Throwable){status="Erro: ${t.message}"};busy=false}},enabled=!busy&&prompt.isNotBlank(),modifier=Modifier.fillMaxWidth()){Text(if(busy)"Gerando…" else "Gerar offline")};if(busy)LinearProgressIndicator(Modifier.fillMaxWidth());result?.let{Card(Modifier.fillMaxWidth().weight(1f)){Image(it.asImageBitmap(),"Imagem gerada",Modifier.fillMaxSize(),contentScale=ContentScale.Fit)}};if(!store.isInstalled(ModelCatalog.image))Text("Baixe o Stable Diffusion na aba Modelos")}}
@Composable private fun ModelsScreen(store:ModelStore){val scope=rememberCoroutineScope();var refresh by remember{mutableIntStateOf(0)};var down by remember{mutableStateOf<String?>(null)};var pct by remember{mutableIntStateOf(0)};var txt by remember{mutableStateOf("")};refresh;LazyColumn(Modifier.fillMaxSize().padding(14.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("IAs instaladas",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Baixe só o que quiser. Depois funcionam sem internet.")};items(ModelCatalog.all){m->val installed=store.isInstalled(m);Card{Column(Modifier.fillMaxWidth().padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text(when(m.kind){EngineKind.BRAIN->"🧠";EngineKind.VISION->"👁";EngineKind.IMAGE->"🎨";EngineKind.VOICE->"🎙"},style=MaterialTheme.typography.headlineMedium);Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(m.title,fontWeight=FontWeight.Bold);Text(m.subtitle,style=MaterialTheme.typography.bodySmall);Text("${m.sizeMb+m.companionSizeMb} MB",style=MaterialTheme.typography.labelSmall)};Text(if(installed)"✓" else "○")};if(down==m.id){LinearProgressIndicator(progress={pct/100f},modifier=Modifier.fillMaxWidth());Text("$pct% • $txt")};if(!installed)Button(onClick={down=m.id;scope.launch{try{store.download(m){p,t->pct=p;txt=t}}catch(t:Throwable){txt="Erro: ${t.message}"};down=null;refresh++}},enabled=down==null){Text("Baixar")}else OutlinedButton(onClick={store.delete(m);refresh++}){Text("Remover")}}}};item{HorizontalDivider();Text("Modelos grandes podem usar muita RAM, aquecer o aparelho e responder mais devagar.")}}}
